version: '3.8'

services:
  app:
    build: 
      - context: .
      - Dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file: 
      - .env
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: prj-1
    command: node PRJ-LAS-main\src\server.js 

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prj-1
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
